spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveHopByHop
      routes:
        - id: library-backend
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

